//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.09 at 02:14:27 PM CEST 
//


package it.accenture.bean.f04;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MovementType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MovementType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Deposit"/>
 *     &lt;enumeration value="Withdrawal"/>
 *     &lt;enumeration value="WithdrawalFee"/>
 *     &lt;enumeration value="GapEvent"/>
 *     &lt;enumeration value="InvestorRebalance"/>
 *     &lt;enumeration value="ProtectedRebalance"/>
 *     &lt;enumeration value="InternalSwitch"/>
 *     &lt;enumeration value="ExternalSwitch"/>
 *     &lt;enumeration value="RewindAdjustment"/>
 *     &lt;enumeration value="PariNavAdjustment"/>
 *     &lt;enumeration value="ProtectionLevelReset"/>
 *     &lt;enumeration value="Cancellation"/>
 *     &lt;enumeration value="RebalanceFee"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MovementType")
@XmlEnum
public enum MovementType {

    @XmlEnumValue("Deposit")
    DEPOSIT("Deposit"),
    @XmlEnumValue("Withdrawal")
    WITHDRAWAL("Withdrawal"),
    @XmlEnumValue("WithdrawalFee")
    WITHDRAWAL_FEE("WithdrawalFee"),
    @XmlEnumValue("GapEvent")
    GAP_EVENT("GapEvent"),
    @XmlEnumValue("InvestorRebalance")
    INVESTOR_REBALANCE("InvestorRebalance"),
    @XmlEnumValue("ProtectedRebalance")
    PROTECTED_REBALANCE("ProtectedRebalance"),
    @XmlEnumValue("InternalSwitch")
    INTERNAL_SWITCH("InternalSwitch"),
    @XmlEnumValue("ExternalSwitch")
    EXTERNAL_SWITCH("ExternalSwitch"),
    @XmlEnumValue("RewindAdjustment")
    REWIND_ADJUSTMENT("RewindAdjustment"),
    @XmlEnumValue("PariNavAdjustment")
    PARI_NAV_ADJUSTMENT("PariNavAdjustment"),
    @XmlEnumValue("ProtectionLevelReset")
    PROTECTION_LEVEL_RESET("ProtectionLevelReset"),
    @XmlEnumValue("Cancellation")
    CANCELLATION("Cancellation"),
    @XmlEnumValue("RebalanceFee")
    REBALANCE_FEE("RebalanceFee");
    private final String value;

    MovementType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MovementType fromValue(String v) {
        for (MovementType c: MovementType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
