//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.09 at 02:14:27 PM CEST 
//


package it.accenture.bean.f04;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StrategyEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="StrategyEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="QuantityPerAsset"/>
 *     &lt;enumeration value="ValueCurrent"/>
 *     &lt;enumeration value="ValuePerAsset"/>
 *     &lt;enumeration value="ValueTarget"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "StrategyEnum")
@XmlEnum
public enum StrategyEnum {

    @XmlEnumValue("QuantityPerAsset")
    QUANTITY_PER_ASSET("QuantityPerAsset"),
    @XmlEnumValue("ValueCurrent")
    VALUE_CURRENT("ValueCurrent"),
    @XmlEnumValue("ValuePerAsset")
    VALUE_PER_ASSET("ValuePerAsset"),
    @XmlEnumValue("ValueTarget")
    VALUE_TARGET("ValueTarget");
    private final String value;

    StrategyEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StrategyEnum fromValue(String v) {
        for (StrategyEnum c: StrategyEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
