//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.10 at 12:29:32 PM CEST 
//


package it.accenture.bean.sap;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AccountStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AccountStatus">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="New"/>
 *     &lt;enumeration value="Active"/>
 *     &lt;enumeration value="PendingClosure"/>
 *     &lt;enumeration value="Closed"/>
 *     &lt;enumeration value="Locked"/>
 *     &lt;enumeration value="CashLock"/>
 *     &lt;enumeration value="GapEvent"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AccountStatus")
@XmlEnum
public enum AccountStatus {

    @XmlEnumValue("New")
    NEW("New"),
    @XmlEnumValue("Active")
    ACTIVE("Active"),
    @XmlEnumValue("PendingClosure")
    PENDING_CLOSURE("PendingClosure"),
    @XmlEnumValue("Closed")
    CLOSED("Closed"),
    @XmlEnumValue("Locked")
    LOCKED("Locked"),
    @XmlEnumValue("CashLock")
    CASH_LOCK("CashLock"),
    @XmlEnumValue("GapEvent")
    GAP_EVENT("GapEvent");
    private final String value;

    AccountStatus(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AccountStatus fromValue(String v) {
        for (AccountStatus c: AccountStatus.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
