//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.10 at 12:29:32 PM CEST 
//


package it.accenture.bean.sap;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Accounts complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Accounts">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Account" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ExternalProductId" type="{http://www.fnz.com/F04}ExternalProductId" minOccurs="0"/>
 *                   &lt;element name="ExternalAccountId" type="{http://www.fnz.com/F04}ExternalAccountId"/>
 *                   &lt;element name="ExternalCustomerId" type="{http://www.fnz.com/F04}ExternalCustomerId" minOccurs="0"/>
 *                   &lt;element name="AccountId" type="{http://www.fnz.com/F04}AccountId" minOccurs="0"/>
 *                   &lt;element name="AccountType" type="{http://www.fnz.com/F04}AccountType"/>
 *                   &lt;element name="HedgeProviderId" type="{http://www.fnz.com/F04}HedgeProviderId" minOccurs="0"/>
 *                   &lt;element name="CloseAccount" type="{http://www.fnz.com/F04}CloseAccount" minOccurs="0"/>
 *                   &lt;element name="Orders" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Order" type="{http://www.fnz.com/F04}Order" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Accounts", propOrder = {
    "account"
})
public class Accounts
    implements Serializable
{

    private final static long serialVersionUID = 145331435L;
    @XmlElement(name = "Account")
    protected List<Account> account;

    /**
     * Gets the value of the account property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the account property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccount().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Account }
     * 
     * 
     */
    public List<Account> getAccount() {
        if (account == null) {
            account = new ArrayList<Account>();
        }
        return this.account;
    }

    public boolean isSetAccount() {
        return ((this.account!= null)&&(!this.account.isEmpty()));
    }

    public void unsetAccount() {
        this.account = null;
    }

}
