//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.10 at 12:29:32 PM CEST 
//


package it.accenture.bean.sap;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DocumentType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DocumentType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="F01"/>
 *     &lt;enumeration value="F01a"/>
 *     &lt;enumeration value="F02"/>
 *     &lt;enumeration value="F03"/>
 *     &lt;enumeration value="F04"/>
 *     &lt;enumeration value="F05"/>
 *     &lt;enumeration value="F06"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DocumentType")
@XmlEnum
public enum DocumentType {

    @XmlEnumValue("F01")
    F_01("F01"),
    @XmlEnumValue("F01a")
    F_01_A("F01a"),
    @XmlEnumValue("F02")
    F_02("F02"),
    @XmlEnumValue("F03")
    F_03("F03"),
    @XmlEnumValue("F04")
    F_04("F04"),
    @XmlEnumValue("F05")
    F_05("F05"),
    @XmlEnumValue("F06")
    F_06("F06");
    private final String value;

    DocumentType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DocumentType fromValue(String v) {
        for (DocumentType c: DocumentType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
